In [1]:
import pandas as pd
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
import autokeras as ak
from sklearn.model_selection import train_test_split

Using TensorFlow backend

2024-10-29 09:59:33.145253: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-10-29 09:59:33.178881: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-10-29 09:59:33.179591: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-10-29 09:59:33.709467: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [2]:
# pip install auto-sklearn
# !pip install scikit_learn==0.24.2

In [3]:
df = pd.read_csv('data/data.csv')

# print(df.head())

In [4]:
df.head()

,timestamp,datapath_id,ip_src,tp_src,ip_dst,tp_dst,ip_proto,icmp_code,icmp_type,flow_duration_sec,flow_duration_nsec,idle_timeout,hard_timeout,packet_count,byte_count,packet_count_per_second,packet_count_per_nsecond,byte_count_per_second,byte_count_per_nsecond,label
0,1.730171e+09,5,2118571384,0,167772163,0,1,0,8,17,587000000,20,100,0,0,0.000000,0.000000e+00,0.000000,0.000000,1
1,1.730171e+09,4,2271877057,0,167772163,0,1,0,8,16,539000000,20,100,0,0,0.000000,0.000000e+00,0.000000,0.000000,1
2,1.730073e+09,2,167772161,5050,167772177,34624,6,-1,-1,26,967000000,20,100,155037,10234738,5962.961538,1.603278e-04,393643.769231,0.010584,0
3,1.730171e+09,2,3285826843,54704,167772166,80,6,-1,-1,17,998000000,20,100,0,0,0.000000,0.000000e+00,0.000000,0.000000,1
4,1.730090e+09,6,167772164,0,167772178,0,1,0,8,20,185000000,20,100,19,1862,0.950000,1.027027e-07,93.100000,0.000010,0

In [5]:
df=df.drop('timestamp', axis=1)
df.head()

,datapath_id,ip_src,tp_src,ip_dst,tp_dst,ip_proto,icmp_code,icmp_type,flow_duration_sec,flow_duration_nsec,idle_timeout,hard_timeout,packet_count,byte_count,packet_count_per_second,packet_count_per_nsecond,byte_count_per_second,byte_count_per_nsecond,label
0,5,2118571384,0,167772163,0,1,0,8,17,587000000,20,100,0,0,0.000000,0.000000e+00,0.000000,0.000000,1
1,4,2271877057,0,167772163,0,1,0,8,16,539000000,20,100,0,0,0.000000,0.000000e+00,0.000000,0.000000,1
2,2,167772161,5050,167772177,34624,6,-1,-1,26,967000000,20,100,155037,10234738,5962.961538,1.603278e-04,393643.769231,0.010584,0
3,2,3285826843,54704,167772166,80,6,-1,-1,17,998000000,20,100,0,0,0.000000,0.000000e+00,0.000000,0.000000,1
4,6,167772164,0,167772178,0,1,0,8,20,185000000,20,100,19,1862,0.950000,1.027027e-07,93.100000,0.000010,0

In [6]:
print(df.shape)

(977774, 19)

In [7]:
X = df.drop("label",axis=1)
y = df['label']

In [8]:
X_train, X_test_check, y_train, y_test_check = train_test_split(
    X, y, test_size=0.35, random_state=42)

In [9]:
X_train.shape

(635553, 18)

In [10]:
X_test, X_validate, y_test, y_validate = train_test_split(
    X_test_check, y_test_check, test_size=2/7, random_state=42)

In [11]:
df_validate = X_validate

In [12]:
y_validate.head()

622971    1
558689    1
242062    0
693297    0
761261    1
Name: label, dtype: int64

In [13]:
df_validate.head()

,datapath_id,ip_src,tp_src,ip_dst,tp_dst,ip_proto,icmp_code,icmp_type,flow_duration_sec,flow_duration_nsec,idle_timeout,hard_timeout,packet_count,byte_count,packet_count_per_second,packet_count_per_nsecond,byte_count_per_second,byte_count_per_nsecond
622971,4,1357932729,0,167772163,0,1,0,8,17,484000000,20,100,0,0,0.0,0.0,0.0,0.0
558689,2,2828743208,55197,167772166,80,6,-1,-1,4,624000000,20,100,0,0,0.0,0.0,0.0,0.0
242062,3,167772175,5050,167772161,56824,1,3,3,15,744000000,20,100,0,0,0.0,0.0,0.0,0.0
693297,3,167772174,0,167772164,0,1,0,8,16,968000000,20,100,0,0,0.0,0.0,0.0,0.0
761261,1,3195608217,0,167772163,0,1,0,8,5,505000000,20,100,0,0,0.0,0.0,0.0,0.0

In [14]:
df_validate = pd.concat([df_validate, y_validate], axis=1)
df_validate.head()

,datapath_id,ip_src,tp_src,ip_dst,tp_dst,ip_proto,icmp_code,icmp_type,flow_duration_sec,flow_duration_nsec,idle_timeout,hard_timeout,packet_count,byte_count,packet_count_per_second,packet_count_per_nsecond,byte_count_per_second,byte_count_per_nsecond,label
622971,4,1357932729,0,167772163,0,1,0,8,17,484000000,20,100,0,0,0.0,0.0,0.0,0.0,1
558689,2,2828743208,55197,167772166,80,6,-1,-1,4,624000000,20,100,0,0,0.0,0.0,0.0,0.0,1
242062,3,167772175,5050,167772161,56824,1,3,3,15,744000000,20,100,0,0,0.0,0.0,0.0,0.0,0
693297,3,167772174,0,167772164,0,1,0,8,16,968000000,20,100,0,0,0.0,0.0,0.0,0.0,0
761261,1,3195608217,0,167772163,0,1,0,8,5,505000000,20,100,0,0,0.0,0.0,0.0,0.0,1

In [15]:
df_validate.to_csv('validate.csv',index=False)

In [ ]:
clf = ak.StructuredDataClassifier(max_trials=20)
clf.fit(X_train, y_train, epochs=50)

Trial 13 Complete [00h 09m 33s]
val_accuracy: 0.9829861521720886

Best val_accuracy So Far: 0.9982844591140747
Total elapsed time: 1d 18h 48m 05s

Search: Running Trial #14

Value             |Best Value So Far |Hyperparameter
True              |True              |structured_data_block_1/normalize
False             |False             |structured_data_block_1/dense_block_1/use_batchnorm
3                 |3                 |structured_data_block_1/dense_block_1/num_layers
32                |32                |structured_data_block_1/dense_block_1/units_0
0                 |0                 |structured_data_block_1/dense_block_1/dropout
1024              |1024              |structured_data_block_1/dense_block_1/units_1
0.5               |0.5               |classification_head_1/dropout
adam_weight_decay |adam              |optimizer
0.001             |0.001             |learning_rate
32                |32                |structured_data_block_1/dense_block_1/units_2

Epoch 1/50
15890/15890 [==============================] - 33s 2ms/step - loss: 0.0883 - accuracy: 0.9661 - val_loss: 0.0237 - val_accuracy: 0.9919
Epoch 2/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0204 - accuracy: 0.9928 - val_loss: 0.0170 - val_accuracy: 0.9932
Epoch 3/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0166 - accuracy: 0.9943 - val_loss: 0.0142 - val_accuracy: 0.9950
Epoch 4/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0142 - accuracy: 0.9956 - val_loss: 0.0109 - val_accuracy: 0.9963
Epoch 5/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0133 - accuracy: 0.9959 - val_loss: 0.0187 - val_accuracy: 0.9932
Epoch 6/50
15890/15890 [==============================] - 33s 2ms/step - loss: 0.0119 - accuracy: 0.9961 - val_loss: 0.0113 - val_accuracy: 0.9965
Epoch 7/50
15890/15890 [==============================] - 33s 2ms/step - loss: 0.0110 - accuracy: 0.9965 - val_loss: 0.0083 - val_accuracy: 0.9972
Epoch 8/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0106 - accuracy: 0.9966 - val_loss: 0.0072 - val_accuracy: 0.9975
Epoch 9/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0095 - accuracy: 0.9967 - val_loss: 0.0085 - val_accuracy: 0.9974
Epoch 10/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0097 - accuracy: 0.9968 - val_loss: 0.0085 - val_accuracy: 0.9973
Epoch 11/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0094 - accuracy: 0.9969 - val_loss: 0.0072 - val_accuracy: 0.9975
Epoch 12/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0093 - accuracy: 0.9970 - val_loss: 0.0069 - val_accuracy: 0.9975
Epoch 13/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0086 - accuracy: 0.9970 - val_loss: 0.0091 - val_accuracy: 0.9975
Epoch 14/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0089 - accuracy: 0.9970 - val_loss: 0.0070 - val_accuracy: 0.9974
Epoch 15/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0084 - accuracy: 0.9971 - val_loss: 0.0067 - val_accuracy: 0.9977
Epoch 16/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0084 - accuracy: 0.9971 - val_loss: 0.0067 - val_accuracy: 0.9977
Epoch 17/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0082 - accuracy: 0.9972 - val_loss: 0.0065 - val_accuracy: 0.9976
Epoch 18/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0083 - accuracy: 0.9972 - val_loss: 0.0064 - val_accuracy: 0.9977
Epoch 19/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0080 - accuracy: 0.9973 - val_loss: 0.0080 - val_accuracy: 0.9975
Epoch 20/50
15890/15890 [==============================] - 33s 2ms/step - loss: 0.0081 - accuracy: 0.9972 - val_loss: 0.0068 - val_accuracy: 0.9976
Epoch 21/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0085 - accuracy: 0.9972 - val_loss: 0.0065 - val_accuracy: 0.9977
Epoch 22/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0076 - accuracy: 0.9973 - val_loss: 0.0067 - val_accuracy: 0.9973
Epoch 23/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0078 - accuracy: 0.9973 - val_loss: 0.0065 - val_accuracy: 0.9977
Epoch 24/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0074 - accuracy: 0.9974 - val_loss: 0.0064 - val_accuracy: 0.9977
Epoch 25/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0076 - accuracy: 0.9974 - val_loss: 0.0075 - val_accuracy: 0.9976
Epoch 26/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0073 - accuracy: 0.9974 - val_loss: 0.0088 - val_accuracy: 0.9973
Epoch 27/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0073 - accuracy: 0.9975 - val_loss: 0.0061 - val_accuracy: 0.9979
Epoch 28/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0071 - accuracy: 0.9975 - val_loss: 0.0065 - val_accuracy: 0.9977
Epoch 29/50
15890/15890 [==============================] - 34s 2ms/step - loss: 0.0070 - accuracy: 0.9975 - val_loss: 0.0057 - val_accuracy: 0.9977
Epoch 30/50
15890/15890 [==============================] - 38s 2ms/step - loss: 0.0067 - accuracy: 0.9976 - val_loss: 0.0051 - val_accuracy: 0.9980
Epoch 31/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0067 - accuracy: 0.9975 - val_loss: 0.0053 - val_accuracy: 0.9979
Epoch 32/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0066 - accuracy: 0.9976 - val_loss: 0.0054 - val_accuracy: 0.9979
Epoch 33/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0066 - accuracy: 0.9976 - val_loss: 0.0051 - val_accuracy: 0.9980
Epoch 34/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0062 - accuracy: 0.9977 - val_loss: 0.0055 - val_accuracy: 0.9980
Epoch 35/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0063 - accuracy: 0.9977 - val_loss: 0.0052 - val_accuracy: 0.9981
Epoch 36/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0060 - accuracy: 0.9977 - val_loss: 0.0055 - val_accuracy: 0.9981
Epoch 37/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0060 - accuracy: 0.9978 - val_loss: 0.0051 - val_accuracy: 0.9979
Epoch 38/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0057 - accuracy: 0.9979 - val_loss: 0.0048 - val_accuracy: 0.9982
Epoch 39/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0054 - accuracy: 0.9979 - val_loss: 0.0046 - val_accuracy: 0.9981
Epoch 40/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0052 - accuracy: 0.9979 - val_loss: 0.0043 - val_accuracy: 0.9982
Epoch 41/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0051 - accuracy: 0.9980 - val_loss: 0.0048 - val_accuracy: 0.9982
Epoch 42/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0050 - accuracy: 0.9981 - val_loss: 0.0045 - val_accuracy: 0.9982
Epoch 43/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0047 - accuracy: 0.9982 - val_loss: 0.0048 - val_accuracy: 0.9982
Epoch 44/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0044 - accuracy: 0.9982 - val_loss: 0.0044 - val_accuracy: 0.9984
Epoch 45/50
15890/15890 [==============================] - 32s 2ms/step - loss: 0.0041 - accuracy: 0.9984 - val_loss: 0.0042 - val_accuracy: 0.9984
Epoch 46/50
15890/15890 [==============================] - 33s 2ms/step - loss: 0.0037 - accuracy: 0.9985 - val_loss: 0.0040 - val_accuracy: 0.9984
Epoch 47/50
15890/15890 [==============================] - 34s 2ms/step - loss: 0.0033 - accuracy: 0.9987 - val_loss: 0.0043 - val_accuracy: 0.9986
Epoch 48/50
15890/15890 [==============================] - 37s 2ms/step - loss: 0.0029 - accuracy: 0.9988 - val_loss: 0.0044 - val_accuracy: 0.9986
Epoch 49/50
15890/15890 [==============================] - 39s 2ms/step - loss: 0.0025 - accuracy: 0.9990 - val_loss: 0.0033 - val_accuracy: 0.9990
Epoch 50/50
 4285/15890 [=======>......................] - ETA: 23s - loss: 0.0024 - accuracy: 0.9990

In [50]:
loss, acc = clf.evaluate(X_test, y_test, verbose=0)
print('Accuracy: %.5f' % acc)

Accuracy: 0.99825

In [51]:
model = clf.export_model()
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_1 (InputLayer)        [(None, 18)]              0

 multi_category_encoding (M  (None, 18)                0
 ultiCategoryEncoding)

 normalization (Normalizati  (None, 18)                37
 on)

 dense (Dense)               (None, 32)                608

 re_lu (ReLU)                (None, 32)                0

 dense_1 (Dense)             (None, 32)                1056

 re_lu_1 (ReLU)              (None, 32)                0

 dense_2 (Dense)             (None, 1)                 33

 classification_head_1 (Act  (None, 1)                 0
 ivation)

=================================================================
Total params: 1734 (6.78 KB)
Trainable params: 1697 (6.63 KB)
Non-trainable params: 37 (152.00 Byte)
_________________________________________________________________

In [26]:
y_pred = model.predict(X_test)

661/661 [==============================] - 1s 1ms/step

In [ ]:
# import numpy as np

# labels = ["benign",  "bruteforce","ddos" , "probe","sqlattack"]

# predicted_labels = np.argmax(y_pred, axis=1)
# predicted_class_names = [labels[label] for label in predicted_labels]

In [ ]:
# print("Accuracy:", accuracy_score(y_test, y_pred))
# print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
# print("Classification Report:\n", classification_report(y_test, y_pred))

In [24]:
# pip install autokeras
# !pip install scikit-learn

In [53]:
model.save('kerasmodel.h5')

['kerasmodel.pkl']

In [62]:
# import pickle
# with open('keras_model.pkl', 'wb') as f:
#     pickle.dump(model, f)

In [54]:
joblib.__version__

'1.4.2'